## PyMEX config file

# Reservoir information paths
# if there is INCLUDE files, it have been put in the temp_run
tpl: 'model\Pituba\Pituba.dat' # tpl file to replace schedule 
inc_folder: 'INCLUDE' #define the include folder name (prefix for robust cases)
schedule: 'Cronograma.inc' # shedule based file
tpl_report: 'TemplateReport.tpl' # tpl file for report result

# # Convertion unities
# vol_m3_to_bbl: True
# gas_to_oil_equiv: True

## Reservoir operation settings
# producers
nb_prod: 15 #number of producers
prod_names: ['P1','P2','P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13','P14','P15']
max_rate_prod: [2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000] 

#injectors
nb_inj: 14 #number of injectors
inj_names: ['I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12','I13','I14']
max_rate_inj: [2400,2400,900,1200,1200,2400,2400,2400,2400,1200,2400,2400,2400,2400]

# platform
max_plat_prod: 15898.73 # max liquid prodution rate platform
max_plat_inj: 18000 # max fluid injection rate platform

# Optimization settings
nb_cycles: 2 #number of cycles
tma: 0.08 # a.a
prices: [45, 0, -6, -2] # oil, gas, water_prod, water_inj (+revenue, -cost)

# Optimization type
opt_type: 0 # deterministic = 0 or robust = 1
num_realization: 50

# Numerical settings
num_cores_parasol: 4
num_cores_simulation: 4

# Options
clean_up_results: 'keep_sr3' # true = delete all files, keep_sr3 = delete all files except .sr3, False = do not delete any file
# clean_up_results: True
# evaluate_npv: True # calculate net present value